# This workflow will do a clean install of bahmniapps dependencies, node dependencies, and build the bahmniapps source code
# This workflow will be triggered only when there's a push to the release-0.92 branch of the repo
# i.e. when a pull request is merged or when a commit is made directly to the master branch
name: Autobuild CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ui
jobs:
  build:

    runs-on: Ubuntu-18.04


    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: v8.9.4

    - name: Use ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    
    - name : Get the node version
      run: node --version
    
    - name: Install Yarn module
      run: yarn install --ignore-engines
   
    - name: Get module Bower
      run: npm install -g bower
      
    - name: Get module Grunt
      run: npm install -g grunt-cli
      
    - name: Get module required for sass (scss)
      run: gem install compass
      
    - name: Set up UI Components/dependencies
      run: bower install
      
    - name: Show current directory
      run: pwd
      
    - name: Build the application (into dist folder) using Grunt
      run: grunt --force
      
    - name: List dist files
      run: cd dist && ls
      
    - name: Where am I
      run: pwd
     
    - name: Initialize git local repository and linking it with remote repository
      run: |
        cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
        
        git init
        git remote add origin https://github.com/leqela-prog/eregister_bahmniapps_release.git
        
      
    - name: Check the current branch and checkout to bahmniapps_auto_build
      run: | 
           cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
           git branch
           
      
      
    - name: Adding file to staging area
      run: |
            cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
            git branch
            Git status
            git add .
        
    #- name: Commit Changes
      
     # run: | 
      # cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
      # git commit -m "release changes to Bahmni apps production code"
      
      
    #- name: Pushing  changes to remote branch
     
     # run: |
      # cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
       #git push --set-upstream bahmniapps_auto_build bahmniapps_auto_build
      
