# This workflow will do a clean install of bahmniapps dependencies, node dependencies, and build the bahmniapps source code
# This workflow will be triggered only when there's a push to the release-0.92 branch of the repo
# i.e. when a pull request is merged or when a commit is made directly to the master branch
name: Autobuild CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ui
jobs:
  build:

    runs-on: Ubuntu-18.04


    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: v8.9.4

    - name: Use ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    
    - name : Get the node version
      run: node --version
    
    - name: Install Yarn module
      run: yarn install --ignore-engines
   
    - name: Get module Bower
      run: npm install -g bower
      
    - name: Get module Grunt
      run: npm install -g grunt-cli
      
    - name: Get module required for sass (scss)
      run: gem install compass
      
    - name: Set up UI Components/dependencies
      run: bower install
      
    - name: Show current directory
      run: pwd
      
    - name: Build the application (into dist folder) using Grunt
      run: grunt --force
      
    - name: List dist files
      run: cd dist && ls
      
    - name: Where am I
      run: pwd
     
    - name: Initialize git local repository and renaming the branch
      run: |
        cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
        
        git init
        git branch -m bahmniapps_artifacts
      
        
      
    - name: Check the current branch
      run: | 
          cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
           git status
           
    - name: Adding file to staging area
      run: |
             cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
             git add .
             
    - name: Check the status of the staging area
      run: | 
             cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
             git status
        
    - name: Commit Changes
      
      run: | 
       cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
       git config --global user.email "seeisoleqelat@gmail.com"
       git config --global user.name "leqela-prog"
       git commit -m "new release changes"
      
      
    - name: Pushing  changes to remote  master branch
      run: |
        cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
        git remote add github https://${{ secrets.BAHMNI_APPS_090 }}@github.com/eRegister/bahmniapps090dev.git
        git push -f github bahmniapps_artifacts 
      
