# This workflow will do a clean install of bahmniapps dependencies, node dependencies, and build the bahmniapps source code
# This workflow will be triggered only when there's a push to the release-0.92 branch of the repo
# i.e. when a pull request is merged or when a commit is made directly to the master branch
name: Autobuild CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ui
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Use ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
   
    - name: Get module Bower
      run: npm install -g bower
      
    - name: Get module Grunt
      run: npm install -g grunt-cli
      
    - name: Get module required for sass (scss)
      run: gem install compass
      
    - name: Set up UI Components/dependencies
      run: bower install
      
    - name: Install project dependeciens
      run: sudo npm install
    
    - name: Show current directory
      run: pwd
      
    - name: Build the application (into dist folder) using Grunt
      run: grunt clean test
      
    - name: List output files
      run: ls

    - name: List dist files
      run: cd dist && ls
      
    - name: Where am I
      run: pwd
     
    - name: Push production code to release repo
      run: |
        cd /home/runner/work/bahmniapps090dev/bahmniapps090dev/ui/dist/
        git config --global user.email "seeisoleqelat@gmail.com"
        git config --global user.name "leqela-prog"
        git init
        git branch -m autobuildmaster
        git add .
        git commit -m "release changes to Bahmni apps production code"
        git push -f github autobuildmaster 
